name: Bytebase GitOps
on:
  push:
    branches: ["main"]
    paths: ["migrations/*.sql"]
env:
  BYTEBASE_URL: "http://187.127.120.202:8080"
  BYTEBASE_TOKEN: "bbs_XKqZxriXIch9MtK8H0Sv"
  BYTEBASE_PROJECT: "projects/gitops-lvtr"
jobs:
  create-rollout:
    runs-on: ubuntu-latest
    container:
      image: bytebase/bytebase-action:3.19.1
    steps:
      - uses: actions/checkout@v4
      - name: Create rollout
        run: |
          bytebase-action rollout \
            --url=$BYTEBASE_URL \
            --service-account="github-bot@enlightlab.com" \
            --service-account-secret=$BYTEBASE_TOKEN \
            --project=$BYTEBASE_PROJECT \
            --targets=instances/postgres-target-zqqc/databases/proddb \
            --file-pattern=migrations/*.sql
