name: Bytebase GitOps
on:
  push:
    branches: ["main"]
    paths: ["migrations/*.sql"]

env:
  BYTEBASE_URL: https://bytebase-production-6e18.up.railway.app
  BYTEBASE_TOKEN: bbs_qaT6NQh3icdxB7CtNjQ4
  BYTEBASE_PROJECT: projects/gitops-80nz

jobs:
  create-rollout:
    runs-on: ubuntu-latest
    container:
      image: bytebase/bytebase-action:3.19.1
    steps:
      - uses: actions/checkout@v4
      - name: Create rollout
        run: |
          bytebase-action rollout \
            --url=$BYTEBASE_URL \
            --service-account="github@service.bytebase.com" \
            --service-account-secret=$BYTEBASE_TOKEN \
            --project=$BYTEBASE_PROJECT \
            --targets=instances/railway-prod-kqzn/databases/proddb \
            --file-pattern=migrations/*.sql
