name: Rollout
on:
  push:
    branches: ["main"]
    paths: ["migrations/*.sql"]
env:
  BYTEBASE_URL: https://data-control.enlightlab.com
  BYTEBASE_PROJECT: projects/gitops-lvtr
jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    environment: prod
    container:
      image: bytebase/bytebase-action:3.19.1
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to prod
        run: |
          bytebase-action rollout \
            --url=$BYTEBASE_URL \
            --service-account="github-ci@service.bytebase.com" \
            --service-account-secret=${{ secrets.BYTEBASE_TOKEN }} \
            --project=$BYTEBASE_PROJECT \
            --targets=instances/postgres-target-zpqs/databases/proddb \
            --file-pattern="migrations/*.sql"
