name: SQL Review
on:
  pull_request:
    branches: ["main"]
    paths: ["migrations/*.sql"]
jobs:
  sql-review:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    container:
      image: bytebase/bytebase-action:3.19.1
    env:
      BYTEBASE_URL: https://data-control.enlightlab.com
    steps:
      - uses: actions/checkout@v4
      - name: SQL Review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bytebase-action check --debug --url=$BYTEBASE_URL --service-account="github-ci" --service-account-secret=${{ secrets.BYTEBASE_TOKEN }} --project=projects/gitops-lvtr --targets=instances/postgres-target-zpqs/databases/proddb --file-pattern="migrations/*.sql"
